FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install

ARG REACT_APP_API_BASE_URL
ARG REACT_APP_NAVER_MAP_CLIENT_KEY

ENV REACT_APP_BACKEND_URL=$REACT_APP_API_BASE_URL
ENV REACT_APP_NAVER_MAP_CLIENT_KEY=$REACT_APP_NAVER_MAP_CLIENT_KEY

COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
RUN npm i -g serve
COPY --from=builder /app/build ./build

EXPOSE 3000
CMD ["sh", "-c", "serve -s build -l ${PORT:-3000}"]
